export default defineNuxtConfig({
  ssr: true,
  devtools: { enabled: process.env.NODE_ENV !== 'production' },

  routeRules: {
    '/dashboard':    { ssr: false },
    '/team/**':      { ssr: false },
    '/viewer/**':    { ssr: false },
    '/compare/**':   { ssr: false },
    '/admin/**':     { ssr: false },
    '/auth/**':      { ssr: false },
    '/profile':      { ssr: false },
    '/packages':     { ssr: false },
    '/inbox':        { ssr: false },
  },

  runtimeConfig: {
    supabaseServiceRoleKey: process.env.SUPABASE_SERVICE_ROLE_KEY || '',
    public: {
      appVersion: '1.2.0',
      supabaseUrl: process.env.SUPABASE_URL || 'https://gqrnlnlfidighosujpdb.supabase.co',
      supabaseAnonKey: process.env.SUPABASE_ANON_KEY || '',
      // Keep in sync with Supabase Auth -> Email OTP length.
      supabaseEmailOtpLength: Number(process.env.SUPABASE_EMAIL_OTP_LENGTH || 8),
      elexessUrl: process.env.ELEXESS_URL || 'https://api.dev.elexess.com/api',
      stripePriceIdPro: process.env.STRIPE_PRICE_ID_PRO || '',
      stripePriceIdTeam: process.env.STRIPE_PRICE_ID_TEAM || '',
      platformAdminIds: process.env.PLATFORM_ADMIN_IDS || '',
      sentry: {
        dsn: process.env.SENTRY_DSN || '',
        environment: process.env.SENTRY_ENVIRONMENT || (process.env.NODE_ENV === 'production' ? 'production' : 'development'),
      },
    },
  },

  modules: ['@nuxtjs/seo', '@nuxt/ui', '@nuxt/content', '@sentry/nuxt/module'],

  site: {
    url: 'https://www.gerbtrace.com',
    name: 'Gerbtrace',
    description: 'Open-source PCB NPI & Manufacturing Data Preparation Platform',
    defaultLocale: 'en',
  },

  sitemap: {
    exclude: [
      '/dashboard',
      '/team/**',
      '/viewer/**',
      '/compare/**',
      '/admin/**',
      '/auth/**',
      '/profile',
      '/packages',
      '/inbox',
    ],
  },

  ogImage: {
    enabled: false,
  },

  experimental: {
    emitRouteChunkError: 'automatic-immediate',
  },

  content: {
    build: {
      markdown: {
        toc: {
          searchDepth: 3,
        },
      },
    },
  },

  sentry: {
    org: 'newmatik',
    project: 'gerbtrace',
    authToken: process.env.SENTRY_AUTH_TOKEN,
    sourcemaps: {
      filesToDeleteAfterUpload: ['.*/**/*.map'],
    },
  },

  sourcemap: { client: 'hidden', server: false },

  vite: {
    server: {
      watch: {
        // The package library contains thousands of JSON files and can exceed
        // macOS fs.watch limits in local dev. These files are served statically
        // and regenerated by scripts, so HMR watch is not required.
        ignored: ['**/public/packages/**'],
        usePolling: true,
        interval: 400,
      },
    },
    build: {
      rollupOptions: {
        output: {
          manualChunks(id) {
            if (id.includes('node_modules/jszip')) return 'vendor-jszip'
            if (id.includes('/lib/gerber/')) return 'gerber-core'
            if (id.includes('/lib/renderer/')) return 'render-core'
            if (id.includes('node_modules/xlsx')) return 'vendor-xlsx'
          },
        },
      },
    },
  },

  icon: {
    clientBundle: {
      scan: {
        globInclude: ['app/**/*.vue', 'app/**/*.ts', 'node_modules/@nuxt/ui/dist/**'],
        globExclude: ['node_modules/@nuxt/ui/dist/**/node_modules/**'],
      },
    },
  },

  css: ['~/assets/css/main.css'],

  components: [
    {
      path: '~/components',
      pathPrefix: false,
    },
  ],

  alias: {
    '@lib': new URL('./lib', import.meta.url).pathname,
  },

  app: {
    baseURL: '/',
    head: {
      htmlAttrs: { lang: 'en' },
      title: 'Gerbtrace \u2014 PCB NPI\u200B\u200C\u200D\uFEFF & Manufacturing Data Preparation',
      meta: [
        { name: 'description', content: 'Open-source PCB NPI\u200B\u200C\u200D\u200B\u200C\u200D\uFEFF\u200B platform. Import Gerber files, manage BOMs and Pick & Place, configure panelization and paste, estimate pricing, and collaborate with your team.' },
        { name: 'theme-color', content: '#3B8EF0' },
        { name: 'verify-v1', content: 'nwmk-7f3a9b2e4d1c8f5a6b0e3d7c9a2f4b8e' },
        { property: 'og:type', content: 'website' },
        { property: 'og:site_name', content: 'Gerbtrace' },
        { property: 'og:image', content: 'https://www.gerbtrace.com/images/docs/pcb-light.png' },
        { name: 'twitter:card', content: 'summary_large_image' },
        { name: 'twitter:image', content: 'https://www.gerbtrace.com/images/docs/pcb-light.png' },
      ],
      link: [
        { rel: 'icon', type: 'image/x-icon', href: '/favicon.ico', sizes: '16x16 32x32 48x48' },
        { rel: 'icon', type: 'image/png', href: '/favicon-light-32x32.png', sizes: '32x32', media: '(prefers-color-scheme: light)' },
        { rel: 'icon', type: 'image/png', href: '/favicon-light-16x16.png', sizes: '16x16', media: '(prefers-color-scheme: light)' },
        { rel: 'icon', type: 'image/png', href: '/favicon-dark-32x32.png', sizes: '32x32', media: '(prefers-color-scheme: dark)' },
        { rel: 'icon', type: 'image/png', href: '/favicon-dark-16x16.png', sizes: '16x16', media: '(prefers-color-scheme: dark)' },
        { rel: 'apple-touch-icon', href: '/apple-touch-icon.png', sizes: '180x180' },
        { rel: 'manifest', href: '/site.webmanifest' },
      ],
    },
  },

  compatibilityDate: '2025-01-01',
})
